name: Deploy to VM on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: /
          remote_path: /home/harsh/chatbot
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Write SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set SSH key permissions
        run: chmod 400 ~/.ssh/id_rsa

      - name: List SSH keys
        run: ls -lha ~/.ssh

      - name: SSH and Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ~/.ssh/id_rsa
          port: 22
          script: |
            cd /home/harsh/chatbot
            git pull origin main
            #Commands to restart the services after pulling
            pkill -f "flask --app backend_app.py"
            pkill -f "streamlit run streamlit_app.py"
            nohup flask --app backend_app.py run --host=127.0.0.1 --port=5000 > flask.log 2>&1 &
            nohup streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0 > streamlit.log 2>&1 &
