name: Deploy to VM on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy with rsync
        uses: Chepsbay/action-rsync@v1.0.2
        env:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          flags: '-avz --delete'
          options: ''
          source: ./
          destination: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/harsh/chatbot
