name: Deploy to VM on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Add host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /home/harsh/duke_chatbot && 
            git pull origin main && 
            pkill -f "flask --app backend_app.py" || true && 
            pkill -f "streamlit run streamlit_app.py" || true && 
            source /home/harsh/venv/bin/activate &&
            nohup flask --app backend_app.py run --host=127.0.0.1 --port=5000 > flask.log 2> flask.err < /dev/null &
            nohup streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0 > streamlit.log 2> streamlit.err < /dev/null &
            echo "Deployment completed at $(date)"
          '
